project_1/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

project_1/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail')
]

project_1/project/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('blog:post_list'), name='root'),
]

project_1/accounts/models.py
from django.conf import settings
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth import get_user_model

# User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    website_url = models.URLField(blank=True)

def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)

post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

project_1/blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

project_1/accounts/views.py
from django.conf import settings
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import  login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.contrib.auth.models import User



# def signup(request):
#     if request.method == "POST":
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save() # DB에 유저의 정보 저장되면서 회원가입이 완료되는 시점.
#             auth_login(request, user)
#             next_url = request.GET.get('next') or 'profile'
#             return redirect(next_url)
#     else:
#         form = UserCreationForm()
#     return render(request, 'accounts/signup.html', {
#         'form': form,
#     })


class SignupView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        next_url = self.request.GET.get('next') or 'profile'
        return resolve_url(next_url)

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect('profile')

signup = SignupView.as_view()

@login_required   # 로그아웃 상황일 때 settings.LOGIN_URL로 이동시켜준다.
def profile(request):
    # request.user
    return render(request, 'accounts/profile.html')

project_1/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post

post_list = ListView.as_view(model=Post)

post_detail = DetailView.as_view(model=Post)

project_1/accounts/templates/accounts/layout.html
 {% extends 'layout.html' %}

 {% block content %}
    <h2>{{ user }}'s Profile</h2>
 {% endblock %}

project_1/accounts/templates/accounts/login.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

project_1/accounts/templates/accounts/profile.html
 {% extends 'accounts/layout.html' %}

 {% block content %}
    <h2>{{ user }}'s Profile</h2>
    <h3>Bio</h3>
    {{ user.profile.bio|default:"empty" }}
 {% endblock %}

project_1/accounts/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>
{% endblock %}

project_1/blog/templates/blog/layout.html
{% extends "layout.html" %}

project_1/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>

    {{ post.content|linebreaks }}

 <hr/>

<a href="{% url "blog:post_list" %}">글 목록</a>

{% endblock %}

project_1/blog/templates/blog/post_list.html
    {% extends "blog/layout.html" %}

    {% block content %}
        <table>
            <tbody>
         {% for post in post_list %}
            <tr>
                <td>
                    <a href="{% url "blog:post_detail" post.pk %}">{{ post.title }}
                </td>
            </tr>
         {% endfor %}
            </tbody>
        </table>

    {% endblock %}

project_1/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Askdjango Blog</title>
</head>
<a href="{% url 'root' %}"><h1>AskDjango Blog</h1></a>
    {% if user.is_authenticated %}
    <a href="{% url 'profile' %}">{{ user }}</a>
    <a href="{% url 'logout' %}?next={{ request.path }}" onclick="return confirm('Are you sure?');">로그아웃</a>
    {% else %}
    <a href="{% url 'signup' %}?next={{ request.path }}">회원가입</a>
        <a href="{% url "login" %}?next={{ request.path }}">로그인</a>
<!--(next 이후의 표현들이 로그인 눌렀을 때 다시 그 직전 창으로 오게끔 도와줌)-->
    {% endif %}
    <hr/>
    {% block content %}
    {% endblock %}
<hr/>
&copy; 2018. AskDjango
</body>
</html>